language: r
sudo: required

apt_packages:
 - openjdk-7-jre
 - r-cran-rjava

before_install:
 - java -version
 - export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/jre
 - export PATH=$PATH:$JAVA_HOME/bin
 - export LD_LIBRARY_PATH=/usr/lib/jvm/java-7-oracle/lib/amd64:/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server
 - R CMD javareconf

install:
 - R -e 'install.packages("rJava")'
 - R -e 'install.packages("data.table")'
 - R -e 'install.packages("stringr")'
 - R -e 'install.packages("qdap")'
 - R -e 'install.packages("testthat")'
 - R -e 'install.packages("lexicon")'

jobs:
  include:
  # Primary test for all builds
  - r: release
    os: linux
    after_success:
    - Rscript -e 'install.packages("covr"); covr::codecov()'

# Whitelist to only do push builds on master branch
# https://stackoverflow.com/a/31882307
branches:
  only:
    - master
    - release

matrix:
  fast_finish: true

cache: packages
warnings_are_errors: false
