jobs:
  include:
    - name: Radlibs-py
      language: python
      python:
      - "3.7"      # current default Python on Travis CI
      before_install:
        - python --version
        - pip install -U pip
        - pip install -U pytest
        - pip install codecov
        - cd radlibs-py
      install:
        - pip install . # install package + test dependencies
      script: coverage run -m pytest 
      after_success:
        - codecov # submit coverage
      branches:
        only:
          - main
          - master
          - release
          
    - name: Radlibs-cli
      language: python
      python:
      - "3.7"      # current default Python on Travis CI
      before_install:
        - python --version
        - pip install -U pip
        - pip install -U pytest
        - pip install codecov
        - cd radlibs-cli
      install:
        - pip install . # install package + test dependencies
      script: coverage run -m pytest  # run tests
      after_success:
        - codecov # submit coverage
      branches:
        only:
          - main
          - master
          - release

    - name: Radlibs-R
      language: r
      cache: packages
      warnings_are_errors: false
      sudo: required
      before_install:
        - cd radlibs-r
      install:
        - R -e 'install.packages("data.table")'
        - R -e 'install.packages("stringr")'
        - R -e 'install.packages("qdap")'
        - R -e 'install.packages("testthat")'
        - R -e 'install.packages("lexicon")'
        - R -e 'install.packages("covr")'
      after_success:
          - Rscript -e 'library(covr); codecov()'
      branches:
        only:
          - main
          - master
          - release
      matrix:
        fast_finish: true
